#!/bin/sh

# Wrapper to conform to the requirements of Terraform external data source
# accepts input as JSON and outputs a JSON result as per
# https://www.terraform.io/docs/providers/external/data_source.html and this comment
# https://github.com/hashicorp/terraform/pull/8768#issuecomment-257131458

set -ue
# Access the key generated by the resource "null_resource" "create_key"
MY_IP="$(curl -s http://icanhazip.com)"
#Output from external data source will be accesible as ${data.external.ssh_public_key.result["ssh_pub_key"]}
jq -n --arg my_ip "$MY_IP" '{"my_ip":$my_ip}'